# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(179, 144)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/camera.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 160, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.screenshotButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.screenshotButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.screenshotButton.setObjectName("screenshotButton")
        self.verticalLayout.addWidget(self.screenshotButton)
        self.showScreensLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.showScreensLabel.setObjectName("showScreensLabel")
        self.verticalLayout.addWidget(self.showScreensLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yesButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.yesButton.setObjectName("yesButton")
        self.horizontalLayout_2.addWidget(self.yesButton)
        self.noButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.noButton.setObjectName("noButton")
        self.horizontalLayout_2.addWidget(self.noButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lastLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lastLabel.setObjectName("lastLabel")
        self.horizontalLayout_3.addWidget(self.lastLabel)
        self.colorFrame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.colorFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.colorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.colorFrame.setObjectName("colorFrame")
        self.horizontalLayout_3.addWidget(self.colorFrame)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 179, 21))
        self.menubar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Such_a_Smart_Tool"))
        self.screenshotButton.setText(_translate("MainWindow", "Screenshot"))
        self.showScreensLabel.setText(_translate("MainWindow", "Show screens"))
        self.yesButton.setText(_translate("MainWindow", "Yes"))
        self.noButton.setText(_translate("MainWindow", "No"))
        self.lastLabel.setText(_translate("MainWindow", "Last:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
